### ISSUE TITLE
submit function

### ISSUE THREAD

**Issue by sophie-greene** [romeokienzler/developerWorks#1]
In the final cell in the notebook
<pre>
from rklib import submit
key = "XbAMqtjdEeepUgo7OOVwng"
part = "LqPRQ"
email = "###_YOUR_CODE_GOES_HERE_###"
secret = "###_YOUR_CODE_GOES_HERE_###"
submit(email, secret, key, part)
</pre>
The submit function defined in `rklib.py` is called with 4 arguments while it's defined to take 6. `all_parts` and `data` are missing

**Comment by romeokienzler** [comment]
Thanks a lot! I'm currently in process of updating the notebook template, it will support 6 arguments..

**Comment by romeokienzler** [comment]
Ok, have updated the template, please have a look, please reopen if problem persists, thanks so much!!!
